kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
spec:
  selector:
    deployment: hello-world
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
