/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/server/context/index"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Json";
    /**
     * Decimal custom scalar type
     */
    decimal<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Decimal";
    /**
     * BigInt custom scalar type
     */
    bigint<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "BigInt";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Json";
    /**
     * Decimal custom scalar type
     */
    decimal<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Decimal";
    /**
     * BigInt custom scalar type
     */
    bigint<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "BigInt";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BigIntFieldUpdateOperationsInput: { // input type
    decrement?: NexusGenScalars['BigInt'] | null; // BigInt
    divide?: NexusGenScalars['BigInt'] | null; // BigInt
    increment?: NexusGenScalars['BigInt'] | null; // BigInt
    multiply?: NexusGenScalars['BigInt'] | null; // BigInt
    set?: NexusGenScalars['BigInt'] | null; // BigInt
  }
  BigIntFilter: { // input type
    equals?: NexusGenScalars['BigInt'] | null; // BigInt
    gt?: NexusGenScalars['BigInt'] | null; // BigInt
    gte?: NexusGenScalars['BigInt'] | null; // BigInt
    in?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    lt?: NexusGenScalars['BigInt'] | null; // BigInt
    lte?: NexusGenScalars['BigInt'] | null; // BigInt
    not?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    notIn?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
  }
  BigIntWithAggregatesFilter: { // input type
    _avg?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    _count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    _max?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    _min?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    _sum?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    avg?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    equals?: NexusGenScalars['BigInt'] | null; // BigInt
    gt?: NexusGenScalars['BigInt'] | null; // BigInt
    gte?: NexusGenScalars['BigInt'] | null; // BigInt
    in?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    lt?: NexusGenScalars['BigInt'] | null; // BigInt
    lte?: NexusGenScalars['BigInt'] | null; // BigInt
    max?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    min?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    not?: NexusGenInputs['NestedBigIntWithAggregatesFilter'] | null; // NestedBigIntWithAggregatesFilter
    notIn?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    sum?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
  }
  CounterCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    value: NexusGenScalars['BigInt']; // BigInt!
  }
  CounterOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    value?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CounterScalarWhereWithAggregatesInput: { // input type
    AND?: Array<NexusGenInputs['CounterScalarWhereWithAggregatesInput'] | null> | null; // [CounterScalarWhereWithAggregatesInput]
    NOT?: Array<NexusGenInputs['CounterScalarWhereWithAggregatesInput'] | null> | null; // [CounterScalarWhereWithAggregatesInput]
    OR?: Array<NexusGenInputs['CounterScalarWhereWithAggregatesInput'] | null> | null; // [CounterScalarWhereWithAggregatesInput]
    createdAt?: NexusGenInputs['DateTimeWithAggregatesFilter'] | null; // DateTimeWithAggregatesFilter
    id?: NexusGenInputs['StringWithAggregatesFilter'] | null; // StringWithAggregatesFilter
    name?: NexusGenInputs['StringWithAggregatesFilter'] | null; // StringWithAggregatesFilter
    updatedAt?: NexusGenInputs['DateTimeWithAggregatesFilter'] | null; // DateTimeWithAggregatesFilter
    value?: NexusGenInputs['BigIntWithAggregatesFilter'] | null; // BigIntWithAggregatesFilter
  }
  CounterUncheckedCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // String!
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    value: NexusGenScalars['BigInt']; // BigInt!
  }
  CounterUncheckedUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    value?: NexusGenInputs['BigIntFieldUpdateOperationsInput'] | null; // BigIntFieldUpdateOperationsInput
  }
  CounterUncheckedUpdateManyInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    value?: NexusGenInputs['BigIntFieldUpdateOperationsInput'] | null; // BigIntFieldUpdateOperationsInput
  }
  CounterUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    value?: NexusGenInputs['BigIntFieldUpdateOperationsInput'] | null; // BigIntFieldUpdateOperationsInput
  }
  CounterUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    value?: NexusGenInputs['BigIntFieldUpdateOperationsInput'] | null; // BigIntFieldUpdateOperationsInput
  }
  CounterWhereInput: { // input type
    AND?: Array<NexusGenInputs['CounterWhereInput'] | null> | null; // [CounterWhereInput]
    NOT?: Array<NexusGenInputs['CounterWhereInput'] | null> | null; // [CounterWhereInput]
    OR?: Array<NexusGenInputs['CounterWhereInput'] | null> | null; // [CounterWhereInput]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    value?: NexusGenInputs['BigIntFilter'] | null; // BigIntFilter
  }
  CounterWhereUniqueInput: { // input type
    id?: string | null; // String
    name?: string | null; // String
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  DateTimeWithAggregatesFilter: { // input type
    _count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    _max?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    _min?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    max?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    min?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    not?: NexusGenInputs['NestedDateTimeWithAggregatesFilter'] | null; // NestedDateTimeWithAggregatesFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  NestedBigIntFilter: { // input type
    equals?: NexusGenScalars['BigInt'] | null; // BigInt
    gt?: NexusGenScalars['BigInt'] | null; // BigInt
    gte?: NexusGenScalars['BigInt'] | null; // BigInt
    in?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    lt?: NexusGenScalars['BigInt'] | null; // BigInt
    lte?: NexusGenScalars['BigInt'] | null; // BigInt
    not?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    notIn?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
  }
  NestedBigIntWithAggregatesFilter: { // input type
    _avg?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    _count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    _max?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    _min?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    _sum?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    avg?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    equals?: NexusGenScalars['BigInt'] | null; // BigInt
    gt?: NexusGenScalars['BigInt'] | null; // BigInt
    gte?: NexusGenScalars['BigInt'] | null; // BigInt
    in?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    lt?: NexusGenScalars['BigInt'] | null; // BigInt
    lte?: NexusGenScalars['BigInt'] | null; // BigInt
    max?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    min?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
    not?: NexusGenInputs['NestedBigIntWithAggregatesFilter'] | null; // NestedBigIntWithAggregatesFilter
    notIn?: Array<NexusGenScalars['BigInt'] | null> | null; // [BigInt]
    sum?: NexusGenInputs['NestedBigIntFilter'] | null; // NestedBigIntFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  NestedDateTimeWithAggregatesFilter: { // input type
    _count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    _max?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    _min?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    max?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    min?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    not?: NexusGenInputs['NestedDateTimeWithAggregatesFilter'] | null; // NestedDateTimeWithAggregatesFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  NestedFloatFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: Array<number | null> | null; // [Float]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    notIn?: Array<number | null> | null; // [Float]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  NestedStringWithAggregatesFilter: { // input type
    _count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    _max?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    _min?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    contains?: string | null; // String
    count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    max?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    min?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    not?: NexusGenInputs['NestedStringWithAggregatesFilter'] | null; // NestedStringWithAggregatesFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  StringWithAggregatesFilter: { // input type
    _count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    _max?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    _min?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    contains?: string | null; // String
    count?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    max?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    min?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    not?: NexusGenInputs['NestedStringWithAggregatesFilter'] | null; // NestedStringWithAggregatesFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
}

export interface NexusGenEnums {
  CounterScalarFieldEnum: "createdAt" | "id" | "name" | "updatedAt" | "value"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  BigInt: any
  DateTime: any
  Decimal: any
  Json: any
}

export interface NexusGenObjects {
  AggregateCounter: { // root type
    _avg?: NexusGenRootTypes['CounterAvgAggregateOutputType'] | null; // CounterAvgAggregateOutputType
    _count?: NexusGenRootTypes['CounterCountAggregateOutputType'] | null; // CounterCountAggregateOutputType
    _max?: NexusGenRootTypes['CounterMaxAggregateOutputType'] | null; // CounterMaxAggregateOutputType
    _min?: NexusGenRootTypes['CounterMinAggregateOutputType'] | null; // CounterMinAggregateOutputType
    _sum?: NexusGenRootTypes['CounterSumAggregateOutputType'] | null; // CounterSumAggregateOutputType
    avg?: NexusGenRootTypes['CounterAvgAggregateOutputType'] | null; // CounterAvgAggregateOutputType
    count?: NexusGenRootTypes['CounterCountAggregateOutputType'] | null; // CounterCountAggregateOutputType
    max?: NexusGenRootTypes['CounterMaxAggregateOutputType'] | null; // CounterMaxAggregateOutputType
    min?: NexusGenRootTypes['CounterMinAggregateOutputType'] | null; // CounterMinAggregateOutputType
    sum?: NexusGenRootTypes['CounterSumAggregateOutputType'] | null; // CounterSumAggregateOutputType
  }
  BatchPayload: { // root type
    count: number; // Int!
  }
  Counter: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    value: NexusGenScalars['BigInt']; // BigInt!
  }
  CounterAvgAggregateOutputType: { // root type
    value?: number | null; // Float
  }
  CounterCountAggregateOutputType: { // root type
    _all: number; // Int!
    createdAt: number; // Int!
    id: number; // Int!
    name: number; // Int!
    updatedAt: number; // Int!
    value: number; // Int!
  }
  CounterMaxAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    value?: NexusGenScalars['BigInt'] | null; // BigInt
  }
  CounterMinAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    value?: NexusGenScalars['BigInt'] | null; // BigInt
  }
  CounterSumAggregateOutputType: { // root type
    value?: NexusGenScalars['BigInt'] | null; // BigInt
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AggregateCounter: { // field return type
    _avg: NexusGenRootTypes['CounterAvgAggregateOutputType'] | null; // CounterAvgAggregateOutputType
    _count: NexusGenRootTypes['CounterCountAggregateOutputType'] | null; // CounterCountAggregateOutputType
    _max: NexusGenRootTypes['CounterMaxAggregateOutputType'] | null; // CounterMaxAggregateOutputType
    _min: NexusGenRootTypes['CounterMinAggregateOutputType'] | null; // CounterMinAggregateOutputType
    _sum: NexusGenRootTypes['CounterSumAggregateOutputType'] | null; // CounterSumAggregateOutputType
    avg: NexusGenRootTypes['CounterAvgAggregateOutputType'] | null; // CounterAvgAggregateOutputType
    count: NexusGenRootTypes['CounterCountAggregateOutputType'] | null; // CounterCountAggregateOutputType
    max: NexusGenRootTypes['CounterMaxAggregateOutputType'] | null; // CounterMaxAggregateOutputType
    min: NexusGenRootTypes['CounterMinAggregateOutputType'] | null; // CounterMinAggregateOutputType
    sum: NexusGenRootTypes['CounterSumAggregateOutputType'] | null; // CounterSumAggregateOutputType
  }
  BatchPayload: { // field return type
    count: number; // Int!
  }
  Counter: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    value: NexusGenScalars['BigInt']; // BigInt!
  }
  CounterAvgAggregateOutputType: { // field return type
    value: number | null; // Float
  }
  CounterCountAggregateOutputType: { // field return type
    _all: number; // Int!
    createdAt: number; // Int!
    id: number; // Int!
    name: number; // Int!
    updatedAt: number; // Int!
    value: number; // Int!
  }
  CounterMaxAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string | null; // String
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    value: NexusGenScalars['BigInt'] | null; // BigInt
  }
  CounterMinAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string | null; // String
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    value: NexusGenScalars['BigInt'] | null; // BigInt
  }
  CounterSumAggregateOutputType: { // field return type
    value: NexusGenScalars['BigInt'] | null; // BigInt
  }
  Mutation: { // field return type
    createOneCounter: NexusGenRootTypes['Counter']; // Counter!
    deleteManyCounter: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteOneCounter: NexusGenRootTypes['Counter'] | null; // Counter
    updateManyCounter: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateOneCounter: NexusGenRootTypes['Counter']; // Counter!
    upsertOneCounter: NexusGenRootTypes['Counter']; // Counter!
  }
  Query: { // field return type
    aggregateCounter: NexusGenRootTypes['AggregateCounter'] | null; // AggregateCounter
    findFirstCounter: NexusGenRootTypes['Counter'] | null; // Counter
    findManyCounter: NexusGenRootTypes['Counter'][]; // [Counter!]!
    findManyCounterCount: number; // Int!
    findUniqueCounter: NexusGenRootTypes['Counter'] | null; // Counter
  }
}

export interface NexusGenFieldTypeNames {
  AggregateCounter: { // field return type name
    _avg: 'CounterAvgAggregateOutputType'
    _count: 'CounterCountAggregateOutputType'
    _max: 'CounterMaxAggregateOutputType'
    _min: 'CounterMinAggregateOutputType'
    _sum: 'CounterSumAggregateOutputType'
    avg: 'CounterAvgAggregateOutputType'
    count: 'CounterCountAggregateOutputType'
    max: 'CounterMaxAggregateOutputType'
    min: 'CounterMinAggregateOutputType'
    sum: 'CounterSumAggregateOutputType'
  }
  BatchPayload: { // field return type name
    count: 'Int'
  }
  Counter: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    name: 'String'
    updatedAt: 'DateTime'
    value: 'BigInt'
  }
  CounterAvgAggregateOutputType: { // field return type name
    value: 'Float'
  }
  CounterCountAggregateOutputType: { // field return type name
    _all: 'Int'
    createdAt: 'Int'
    id: 'Int'
    name: 'Int'
    updatedAt: 'Int'
    value: 'Int'
  }
  CounterMaxAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    name: 'String'
    updatedAt: 'DateTime'
    value: 'BigInt'
  }
  CounterMinAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    name: 'String'
    updatedAt: 'DateTime'
    value: 'BigInt'
  }
  CounterSumAggregateOutputType: { // field return type name
    value: 'BigInt'
  }
  Mutation: { // field return type name
    createOneCounter: 'Counter'
    deleteManyCounter: 'BatchPayload'
    deleteOneCounter: 'Counter'
    updateManyCounter: 'BatchPayload'
    updateOneCounter: 'Counter'
    upsertOneCounter: 'Counter'
  }
  Query: { // field return type name
    aggregateCounter: 'AggregateCounter'
    findFirstCounter: 'Counter'
    findManyCounter: 'Counter'
    findManyCounterCount: 'Int'
    findUniqueCounter: 'Counter'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneCounter: { // args
      data: NexusGenInputs['CounterCreateInput']; // CounterCreateInput!
    }
    deleteManyCounter: { // args
      where?: NexusGenInputs['CounterWhereInput'] | null; // CounterWhereInput
    }
    deleteOneCounter: { // args
      where: NexusGenInputs['CounterWhereUniqueInput']; // CounterWhereUniqueInput!
    }
    updateManyCounter: { // args
      data: NexusGenInputs['CounterUpdateManyMutationInput']; // CounterUpdateManyMutationInput!
      where?: NexusGenInputs['CounterWhereInput'] | null; // CounterWhereInput
    }
    updateOneCounter: { // args
      data: NexusGenInputs['CounterUpdateInput']; // CounterUpdateInput!
      where: NexusGenInputs['CounterWhereUniqueInput']; // CounterWhereUniqueInput!
    }
    upsertOneCounter: { // args
      create: NexusGenInputs['CounterCreateInput']; // CounterCreateInput!
      update: NexusGenInputs['CounterUpdateInput']; // CounterUpdateInput!
      where: NexusGenInputs['CounterWhereUniqueInput']; // CounterWhereUniqueInput!
    }
  }
  Query: {
    aggregateCounter: { // args
      cursor?: NexusGenInputs['CounterWhereUniqueInput'] | null; // CounterWhereUniqueInput
      distinct?: NexusGenEnums['CounterScalarFieldEnum'] | null; // CounterScalarFieldEnum
      orderBy?: Array<NexusGenInputs['CounterOrderByInput'] | null> | null; // [CounterOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['CounterWhereInput'] | null; // CounterWhereInput
    }
    findFirstCounter: { // args
      cursor?: NexusGenInputs['CounterWhereUniqueInput'] | null; // CounterWhereUniqueInput
      distinct?: NexusGenEnums['CounterScalarFieldEnum'] | null; // CounterScalarFieldEnum
      orderBy?: Array<NexusGenInputs['CounterOrderByInput'] | null> | null; // [CounterOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['CounterWhereInput'] | null; // CounterWhereInput
    }
    findManyCounter: { // args
      cursor?: NexusGenInputs['CounterWhereUniqueInput'] | null; // CounterWhereUniqueInput
      distinct?: NexusGenEnums['CounterScalarFieldEnum'] | null; // CounterScalarFieldEnum
      orderBy?: Array<NexusGenInputs['CounterOrderByInput'] | null> | null; // [CounterOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['CounterWhereInput'] | null; // CounterWhereInput
    }
    findManyCounterCount: { // args
      cursor?: NexusGenInputs['CounterWhereUniqueInput'] | null; // CounterWhereUniqueInput
      distinct?: NexusGenEnums['CounterScalarFieldEnum'] | null; // CounterScalarFieldEnum
      orderBy?: Array<NexusGenInputs['CounterOrderByInput'] | null> | null; // [CounterOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['CounterWhereInput'] | null; // CounterWhereInput
    }
    findUniqueCounter: { // args
      where: NexusGenInputs['CounterWhereUniqueInput']; // CounterWhereUniqueInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}