apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: spantree/hello-world-kustomize-k8s
      context: .
  tagPolicy:
    customTemplate:
      template: '0.1.3-SNAPSHOT'
  local:
    push: true
deploy:
  kustomize:
    paths:
      - ./k8s/overlays/dev
