apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: spantree/hello-world-kustomize-k8s
      context: .
  tagPolicy:
    sha256: {}
  local:
    push: true
# deploy:
#   kustomize:
#     paths:
#       - ./kustomize/base
